name: Checkout
description: Alternative to actions/checkout
runs:
  using: composite
  steps:
    - name: Checkout Git repo
      shell: bash
      run: |-
        git config --global init.defaultBranch main
        git init .
        git remote add origin '${{ github.server_url }}/${{ github.repository }}.git'
        git config set --local advice.detachedHead false
        git config set --local 'http.${{ github.server_url }}.extraHeader' "Authorization: Basic $(echo -n 'x-access-token:${{ github.token }}' | base64 -w0)"
        git fetch --depth 1 origin '${{ github.sha }}'
        git checkout --progress FETCH_HEAD

    - name: Configure Git user name/email
      shell: bash
      run: |-
        git config set user.name 'github-actions[bot]'
        git config set user.email '${{ github.actor_id }}+github-actions[bot]@users.noreply.github.com'
