name: Checkout
description: Alternative to actions/checkout
inputs:
  submodules:
    description: 'Recursively checkout submodules'
    type: boolean
    default: false
    required: false
runs:
  using: composite
  steps:
    - name: Set Git HTTP auth header
      shell: bash
      run: |-
        git config set --global 'http.${{ github.server_url }}.extraHeader' "Authorization: Basic $(echo -n 'x-access-token:${{ github.token }}' | base64 -w0)"

    - name: Checkout Git repo
      shell: bash
      run: |-
        git init --initial-branch dummy .
        git config set --local advice.detachedHead false
        git remote add origin '${{ github.server_url }}/${{ github.repository }}.git'
        git fetch --depth 1 origin '${{ github.sha }}'

        case "$GITHUB_REF" in
          refs/heads/*)
            git branch "$GITHUB_REF_NAME" FETCH_HEAD
            git checkout "$GITHUB_REF_NAME"
            ;;
          refs/tags/*)
            git fetch --depth 1 origin "refs/tags/$GITHUB_REF_NAME:refs/tags/$GITHUB_REF_NAME"
            git checkout "refs/tags/$GITHUB_REF_NAME"
            ;;
          *)
            # GITHUB_REF is neither branch nor tag (e.g. pull request merge ref).
            # Leave FETCH_HEAD as detached head.
            git checkout FETCH_HEAD
            ;;
        esac

        if [ '${{ inputs.submodules }}' = 'true' ]; then
          git submodule update --init --recursive --depth 1
        fi

    - name: Configure Git user name/email
      shell: bash
      run: |-
        git config set user.name 'github-actions[bot]'
        git config set user.email '${{ github.actor_id }}+github-actions[bot]@users.noreply.github.com'
