name: build-docker-image
on:
  workflow_call:
    inputs:
      build_args:
        description: "List of build-time variables"
        default: ''
        required: false
        type: string
      build_contexts:
        description: "List of additional build contexts (e.g., name=path)"
        default: ''
        required: false
        type: string
      context:
        description: "Build's context is the set of files located in the specified PATH or URL (default Git context)"
        default: ''
        required: false
        type: string
      file:
        description: "Path to the Dockerfile"
        default: ''
        required: false
        type: string
      registry:
        description: 'Server address of container registry. If not set then will default to GitHub Container Registry'
        default: 'ghcr.io'
        required: false
        type: string
      registry_username:
        description: 'Username used to login against the container registry'
        default: ${{ github.actor }}
        required: false
        type: string
      registry_password:
        description: 'Password or token used to login against the container registry'
        default: ''
        required: false
        type: string
      registry_repository:
        description: 'Path to the image repository within the container registry'
        default: ${{ github.repository }}
        required: false
        type: string
      push:
        description: 'Push built image to the container registry'
        default: ${{ ( github.ref_type == 'branch' && github.ref_name == github.event.repository.default_branch ) || github.ref_type == 'tag' }}
        required: false
        type: boolean
concurrency:
  group: ${{ inputs.push && format('{0}/{1}', inputs.registry, inputs.registry_repository) || github.sha }}
permissions:
  packages: write
defaults:
  run:
    shell: bash
jobs:
  platform:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
        - linux/386
        - linux/amd64
        - linux/arm/v6
        - linux/arm/v7
        - linux/arm64/v8
        - linux/ppc64le
        - linux/s390x
        - linux/riscv64
    steps:
    - uses: docker/login-action@v3
      if: ${{ inputs.push }}
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry == 'ghcr.io' && inputs.registry_username == github.actor && inputs.registry_password == '' && github.token || inputs.registry_password }}
        logout: false
    - uses: docker/setup-buildx-action@v3
      with:
        cleanup: false
    - name: Build and push image for ${{ matrix.platform }}
      id: build
      uses: docker/build-push-action@v6
      env:
        DOCKER_BUILD_RECORD_UPLOAD: 'false'
        DOCKER_BUILD_SUMMARY: 'false'
        SOURCE_DATE_EPOCH: '0'
      with:
        build-args: ${{ inputs.build_args }}
        build-contexts: ${{ inputs.build_contexts }}
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        tags: ${{ inputs.registry }}/${{ inputs.registry_repository }}
        provenance: false
        platforms: ${{ matrix.platform }}
        outputs: type=image,oci-mediatypes=true,push-by-digest=true,name-canonical=true,rewrite-timestamp=true,push=${{ inputs.push }}
    - name: Export RepoDigest
      if: ${{ inputs.push }}
      env:
        PLATFORM: ${{ matrix.platform }}
        REPO_DIGEST: ${{ steps.build.outputs.digest }}
      run: |-
        PLATFORM_DASH=${PLATFORM//\//-}
        echo "PLATFORM_DASH=${PLATFORM_DASH}" >> "${GITHUB_ENV}"
        echo -n "${REPO_DIGEST}" > "RepoDigest-${PLATFORM_DASH}"
    - name: Upload RepoDigest
      if: ${{ inputs.push }}
      uses: actions/upload-artifact@v6
      with:
        name: RepoDigest-${{ env.PLATFORM_DASH }}
        path: RepoDigest-*
        if-no-files-found: error
        retention-days: 1
        compression-level: 0
  index:
    if: ${{ inputs.push }}
    needs: platform
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry == 'ghcr.io' && inputs.registry_username == github.actor && inputs.registry_password == '' && github.token || inputs.registry_password }}
        logout: false
    - uses: docker/setup-buildx-action@v3
      with:
        cleanup: false
    - uses: docker/metadata-action@v5
      env:
        DOCKER_METADATA_ANNOTATIONS_LEVELS: index
      with:
        images: ${{ inputs.registry }}/${{ inputs.registry_repository }}
        tags: |-
          type=raw,value=edge,enable={{is_default_branch}}
          type=ref,event=tag
    - name: Download digests
      uses: actions/download-artifact@v8
      with:
        pattern: RepoDigest-*
        merge-multiple: true
    - name: Create image index and push
      env:
        IMAGE: ${{ inputs.registry }}/${{ inputs.registry_repository }}
      run: |-
        readarray -t lines <<< "$DOCKER_METADATA_OUTPUT_ANNOTATIONS"; annotations=(); for line in "${lines[@]}"; do annotations+=(--annotation "$line"); done
        readarray -t lines <<< "$DOCKER_METADATA_OUTPUT_TAGS"; tags=(); for line in "${lines[@]}"; do tags+=(--tag "$line"); done
        docker buildx imagetools create "${annotations[@]}" "${tags[@]}" $(sed -e "s|^|${IMAGE}@|" RepoDigest-*)
